name: 'Build combined search index'
author: 'TuringLang'
description: 'Fetch documentation search indices from multiple repositories and combine them into a single search index for improved search functionality.'

runs:
  using: "composite"
  steps:
      # NOTE: This action assumes that you already have Julia set up!
      - name: Run script
        shell: bash
        run: julia --color=yes --project=${{ github.action_path }}/scripts ${{ github.action_path}}/scripts/search.jl
