name: 'Add Navbar Action'
author: 'Shravan Goswami'
description: 'Adds a top navigation bar to Documenter.jl-generated sites'
inputs:
  doc-path:
    description: 'Path to the Documenter.jl output'
    required: false
    # Most Julia projects have it here
    default: 'docs/build'
  navbar-url:
    description: 'URL or local path of the navbar HTML to be inserted.'
    required: false
    default: '${{ github.action_path }}/scripts/TuringNavbar.html'
  exclude-paths:
    description: 'Comma-separated list of paths to exclude from navbar insertion.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Update Navbar
      working-directory: ${{ inputs.doc-path }}
      run: |
        julia ${{ github.action_path }}/scripts/insert_navbar.jl . "${{ inputs.navbar-url }}" --exclude "${{ inputs.exclude-paths }}"
      shell: bash
